### ISSUE TITLE
No Route Matches "Missing Required ID"

### ISSUE THREAD

**Issue by KoryJCampbell** [ga-wdi-exercises/project2#385]
I'm trying to link to my book index.html.erb page but I keep getting this error. 

I'm sure it's something simple I missed. 

```
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

end
```

```
Rails.application.routes.draw do
root to: 'users#index'

resources :users do
  resources :bookshelves
end

resources :bookshelves do
  resources :books
end

resources :books

resources :bookshelves



end
```

**Comment by KoryJCampbell** [comment]
```
<section>
    <%= link_to "Books", bookshelf_books_path(@book)%>
</section>


<!-- Root Link -->

<%= link_to "Home", root_path %>
```

**Comment by amaseda** [comment]
Can you include your error?

I think it's because you need to tell `bookshelf_books_path` what your bookshelf is before `@book`.

Also, do you need all those `resources` in `routes.rb`? The nested bookshelves resources block should eliminate the need for the second `resources: bookshelves`.

Let me know if that helps.

**Comment by KoryJCampbell** [comment]
No route matches {:action=>"index", :bookshelf_id=>nil, :controller=>"books"} missing required keys: [:bookshelf_id]

**Comment by KoryJCampbell** [comment]
```

<section>
    <%= link_to "Books", bookshelf_books_path(@book)%>
</section>


<!-- Root Link -->
```

**Comment by amaseda** [comment]
Yup, so that error indicates that your app needs to know what the bookshelf is (`:bookshelf_id=>nil`). You need to pass in a value for the current bookshelf into `bookshelf_books_path`.

This section from the nested resources lesson plan has some useful info on this: https://github.com/ga-dc/curriculum/tree/master/05-mvc-with-rails/rails-routes-and-resources#lets-click-on-an-artist

Let me know if you need more help.

**Comment by KoryJCampbell** [comment]
Thanks!
