### ISSUE TITLE
Issue with isolating font family from element

### ISSUE THREAD

**Issue by caitlindaitch** [ga-wdi-exercises/project2#495]
I tried this code to select the font family:

``` js
cardOneFont = activeCard.style.fontFamily;
```

activeCard is correct and is returning the element that has the font-family attribute

I expected this to return the name of the font (ie. Arial) when I used console.log

It returned nothing.

My repo link is https://github.com/caitlindaitch/ConcentrationGame and my question is about line 23.

**Comment by RobertAKARobin** [comment]
The thing about `.style` is that it only works if you've set the CSS using Javascript, e.g. `element.style.fontFamily = "Comic Sans MS";`, or if you're using inline styles, e.g. `style="font-family:'Comic Sans MS'"`.

That's because `.style` actually changes the `style=` attribute. If you do `document.body.style.color = "red"` and then inspect element on the `<body>`, you'll see it's now `<body style="color: red">`.

If you're trying to get a style that was set in `<style>` tags or in a stylesheet, it's trickier. You'll need to use this guy: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

**Comment by RobertAKARobin** [comment]
Uh. Incidentally, you're on the wrong repo. You want https://github.com/ga-wdi-exercises/project1, and this is Project 2. You sure you're doing the right project? :stuck_out_tongue:
