### ISSUE TITLE
method from model comes up undefined

### ISSUE THREAD

**Issue by kairajohnson** [ga-wdi-exercises/project2#504]
I tried to define a method I will be using in my view in my model. I expected the method to be recognized since its in my posts.rb file and view but it showed as undefined instead.

My repo link is https://github.com/kairajohnson/live-unapologetically

my question is about lines 45 in my index.html.erb file for posts and posts.rb file in my model.

**Comment by kairajohnson** [comment]
ive tried calling 
Post.recent_posts
post.recent_posts
@post.recent_posts

and the same in model for posts.____  
so, Post, @post, post.

**Comment by RobertAKARobin** [comment]
Make sure you validate your source code. You have an entire `<!DOCTYPE html>` and everything in your `posts/index.html.erb`. You shouldn't. Each view is going to be inserted into `layouts/application.html.erb`. The result will be something like:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>This is wrong.</title>
  </head>
  <body>
<!DOCTYPE html>
<html>
  <!-- A whole other webpage is in here -->
</html>
</html>
```

**Comment by RobertAKARobin** [comment]
``` rb
class Post < ActiveRecord::Base
  def recent_posts
    image_tag post.featured_image
    post.title
    post.content
  end
end
```

There are two issues here:
- You're trying to define a helper method in a model. Model methods should only manipulate data; they should not generate HTML. The job of a helper method is to generate HTML.
- Even if it's a helper method, any Ruby method can return only one object. The only thing that would get returned out of this method is `post.content`.

I would recommend not making this a method at all. Instead of putting `recent_posts` into a helper method or something, just write it directly in your `index.html.erb` file.

**Comment by kairajohnson** [comment]
Thanks robin
