### ISSUE TITLE
Continued issue with join table

### ISSUE THREAD

**Issue by alexbannon** [ga-wdi-exercises/project2#53]
Yeah I'm still hitting a wall. This is my first time actually using a join table so I'm not sure how it works.

After setting up the migrations, I expected a simple way to create instances and have them reference each other, but I'm not quite sure how to go about that. Typically, when not many to many, I would just write user_id as a parameter of my User.Create(). But I don't really know how to do UserEvent.create() because it's not a model, just a table.

Basically, I have users and events. A user has many events that they belong to and an event has many users that are a part of the event.

Here's my CreateUsers migration: 

```
create_table :users do |t|
  t.string :first_name
  t.string :last_name
  t.string :username
  t.string :email
  t.string :password_digest
end
and here's my CreateEvents migration:
create_table :events do |t|
  t.string :title
  t.string :event_content
  t.datetime :created_at
  t.datetime :updated_at
end
and finally my join table migration:
create_join_table :users, :events do |t|
  t.references :user, index: true, foreign_key: true
  t.references :event, index: true, foreign_key: true
end
```

Blah!

**Comment by RobertAKARobin** [comment]
Checking now!

**Comment by RobertAKARobin** [comment]
Why not just let ActiveRecord do the heavy lifting for you?

Instead of `create_join_table`, create a table called "attendance" (or something) that has two columns: `user_id` and `event_id`. Then create a model for it. Specify that a user has many attendances, an event has many attendances, and an attendance belongs to a user and an event. To make a user join an event, just create a new Attendance for them.

Now you can do `@user.attendance.create(event_id: @event.id)`!

**Comment by jshawl** [comment]
:+1: I too recommend Robin's suggestion of creating an attendance model with two foreign keys
