### ISSUE TITLE
Understanding the .exists? method

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project2#582]
I have this logic in my project show.html.erb page 

<% if Team.exists?(@project.teams.find(@project)) %>
  <%= link_to "Team", team_path(@project.team) %>
<% else %>
  <%= link_to "New Team", add_team_project_path(@project) %>
<% end %>

But I get this error when click on a Project

http://imgur.com/YPUrvzr

Shouldn't the .exists? method be catching this and then displaying the link under the else?

**Comment by nolds9** [comment]
can you post a link to your project...not sure I follow your logic on that `if` statement

**Comment by nolds9** [comment]
`.exists?` will check if any instance of a class meets the passed criteria, I think you can change your condition a little bit to get your targeted behavior:

Pseudo-code since I dont know your code base...

``` ruby
# If a project does not have a team, then show them the link to add a new team
# otherwise link to the team show
<% if @project.teams.any? %>
  <%= link_to "New Team", add_team_project_path(@project) %>
<% else %>
 # issue becomes which team to go to...
 <%= link_to "Team", team_path(@project.teams.first) %>
<% end %>
```

related: http://stackoverflow.com/questions/18624489/rails-how-can-i-tell-if-a-record-has-a-child-record-in-any-one-of-its-child-tab

**Comment by jshawl** [comment]
feel free to open another issue!
