### ISSUE TITLE
Struggling with Many to Many & Nesting 

### ISSUE THREAD

**Issue by RasheedaAlexander** [ga-wdi-exercises/project2#639]
I created a Join table called destination to associate my Vendors, Resorts with certain Users. But I cannot seem to only make 1 Resort and several vendors visible to a specific user.

https://github.com/RasheedaAlexander/wedding/tree/many_to_many

**Comment by andrewsunglaekim** [comment]
what have you tried, what errors are you getting

**Comment by RasheedaAlexander** [comment]
No errors. I'm just not sure if I need to:
1. Include a views folder for Users in order to display the current user's Resorts and Vendors
2. A controller for users or if I should add the functionality to the Resort and Vendor controller instead
3. And I'm not sure whether the user_id should be the foreign key or the join table (destination) is my foreign key

**Comment by andrewsunglaekim** [comment]
all these questions are really dependent on your domain model. IE. if my website needs a feature where a user can log in and see resorts and vendors, then you probably need a views folder for the users show page. You're going to need a controller for users either way in order to CRUD them.

Also note that you can always custom make your own routes with your own controllers and actions. 

A Join table is something that associates 2 models. In the example of `doctors`, `patients` and `appointments`, `appointments` is the join table that has both a `doctor_id` and a `patient_id`
