### ISSUE TITLE
Session Controller

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project2#713]
While creating session controller, do I need to create a user controller?
If I want to include a sign up form, do I have to use devise?

**Comment by jshawl** [comment]
no need to use devise! - reference this LP for users without devise https://github.com/ga-wdi-lessons/rails-users-sessions-flash-cookies

**Comment by pohckuan** [comment]
got this error while routing to the sign in form
![image](https://cloud.githubusercontent.com/assets/15622467/19452945/00829314-9481-11e6-9bfe-32fbacc5a8b0.png)

does this mean that I need to create a user controller?

**Comment by amaseda** [comment]
Is this a form for a User or a Retailer? Currently it looks like a form for a Retailer, and it's complaining that it can't find a username attribute for a Retailer.

That aside, if you're going to have a separate User model then it should have its own controller.

**Comment by nolds9** [comment]
Since you are treating your `Retailer` model as a "user", that form should contain all necessary information to sign in to a Retailer...meaning you get to choose which attributes you want the retailer to enter, because that is the same way you are going to lookup the retailer.

i.e. if a Retailer has a `name` property, then I might ask the Retailer to enter in their name to "sign in", then on the backend I am looking up that Retailer by the named entered in order to set the current Retailer

**Comment by pohckuan** [comment]
so I will use the "name" property of Retailer that I have in the seeds file? If yes, does that mean I need to include password in the seeds file too..?

**Comment by nolds9** [comment]
@pohckuan Ultimately, it's up to you! You get to decide what information needs to be stored or is necessary for a retailer to be created / sign in.  I recommend keeping it simple, maybe just `name` and `password`

**Comment by pohckuan** [comment]
i added password to my seeds file, and i'm able to access the sign in form. But I dont think the sign-in is successful since I do not get  any message. 
The following is what I have in the session controller:
![image](https://cloud.githubusercontent.com/assets/15622467/19454320/ad03b208-9486-11e6-887b-5e24c55e3d57.png)

**Comment by amaseda** [comment]
Closing this one but feel free to re-open if you have any more questions on this topic!
