### ISSUE TITLE
validation failed

### ISSUE THREAD

**Issue by marlungu** [ga-wdi-exercises/project2#721]
.Can't figure the bug, this  is the error I'm getting it
![image](https://cloud.githubusercontent.com/assets/18635698/19459264/9ab9dec4-949f-11e6-998d-b31125b50aa4.png)
Here is the code snippet for the controller
![image](https://cloud.githubusercontent.com/assets/18635698/19459319/ed5da37c-949f-11e6-8c04-fabc1baf0e22.png)

**Comment by amaseda** [comment]
What's the value of `current_user` when you get this error? Are you logged-in?

**Comment by marlungu** [comment]
No, this error appears when I'm logged out and trying to post something. But when I'm logged in tried to post something then, a different error 
![image](https://cloud.githubusercontent.com/assets/18635698/19459715/37e29198-94a3-11e6-93a5-9cdb20b8f1d1.png)

**Comment by amaseda** [comment]
Gotcha. In the first error, it's erroring out because you're trying to set `user:` to `current_user` when there is no current user. Not sure if this is functionality you want, but one way to fix it is to make it so that if you are not logged in, that line of code is never hit. You can do that using a technique similar to [this](https://github.com/ga-wdi-lessons/rails-users-sessions-flash-cookies/blob/master/adding-permissions.md#3-disable-createupdatedelete-routes-for-signed-out-users).

In your second error, Rails is actually proposing some alternate syntax (one of which is correct). The issue here is that you're not leveraging your ActiveRecord associations properly. Remember, Question and Answer have a one-to-many relationship...

**Comment by marlungu** [comment]
thanks
