### ISSUE TITLE
Uninitialized Constant Errorf

### ISSUE THREAD

**Issue by jgrune** [ga-wdi-exercises/project2#796]
I built a new "deck" model with the following code below, however when I run Deck.new I get an error saying that shuffle! is not a valid method.  It doesn't seem to allow the exlamation, however I would like to permanently mutate my array.  I thought this worked in our previous examples...

Model:
```
require 'card'

class Deck
  attr_reader :cards

  def initialize
    @cards = Card.all
    shuffle
  end

  def shuffle
    @cards.shuffle!
  end

  def deal num
    dealt_cards = []
    dealt_cards << @cards.pop
  end

end

```

**Comment by andrewsunglaekim** [comment]
I think that's because `@cards` is an active record relation and not an array.

**Comment by jgrune** [comment]
ah ok.. I updated to the following code, however even this seems to only temporarily reorder the rows - do I need to then store the reordered rows in some other instance variable or something?

```
def shuffle
    @cards.order('random()')
  end
```

**Comment by andrewsunglaekim** [comment]
can you try 

``` ruby
def shuffle
  @cards = @cards.order('random()')
end
```

**Comment by jgrune** [comment]
That works - but can you help me understand why fundamentally an active record relation can't be treated like a regular array?  For example, I won't be able to run .pop on `@cards` for the same reason I can't run .shuffle in the above example.

**Comment by andrewsunglaekim** [comment]
they are not the same class! One is of the `Array` class and one is of the Active Record relation class. Some not all `Array` class methods transfer to the Active Record Relation class.

**Comment by jgrune** [comment]
gotcha - so do you recommend something like this to be able to treat my deck like a regular array?
`@cards = Card.all.to_a`

This seems to work ^^

**Comment by andrewsunglaekim** [comment]
sure! That's your decision to make. In the event you want to use Active Record queries against your @cards array, you will no longer be able to though. And _i think_ it's impossible to coerce an array of active record objects back into an active record relation. 

So there's three options here, and depending on how your using this property of your deck model should decide which option.

Option 1. I will forever and always only use `Array` class methods on this collection of AR objects. And therefore will convert it to an array.

Option 2. I _may_ end up needing AR niceties later in my program despite only needing `Array` class methods currently. So i need to maintain the AR relation and work in the confines of it. (In my opinion the best option, shuffling and removing 1 element in a relation is very easy to do in a collection.)

Opetion 3. (Don't do this) Duplicate the data so that you have a property as both an array and an active record relation so that you have access to both.

**Comment by jgrune** [comment]
Thanks andy! That's very helpful .. Feel free to close the issue!
