### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by HabRonan** [ga-wdi-exercises/project2#814]
hey adrian,
If I were to override the devise user model and wanted to add User model that inherits from Devise how would I go about adding it.

**Comment by amaseda** [comment]
What's the reasoning behind wanting to do this? What sort of functionality do you want to add to Devise?

**Comment by HabRonan** [comment]
For a Crowdfunding Application, 
I wanted to add these fields( Is_donor?, Username, first_name, last_name, phone, billing_address, mailing_address, credit_card) and be able to have access to them.  Not just email and password

**Comment by amaseda** [comment]
Ah, so if you want to add additional attributes to a Devise user, you don't need to create a separate User model. Instead, you can...

  1. Create migrations that add columns to Devise's user table
  2. Update your forms so that you have fields for these new attributes
  3. Update Devise's strong params method so that you can access these new attributes in the controller

[This post does a good job of summarizing it all](http://jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html). You might do things differently than they say in here (for example, you won't be writing things using Slim) but it's a good place to start.

**Comment by HabRonan** [comment]
I did create updated migrations to the devise user table. Thanks I will check the link.

**Comment by amaseda** [comment]
@HabRonan Sounds good! Going to close this for now but please re-open it once you have new questions.
