### ISSUE TITLE
users & comments

### ISSUE THREAD

**Issue by nfiona** [ga-wdi-exercises/project2#843]
I tried to connect user's email address to comments. 
I expected: when a user creates a comment, the user's email address should be displayed on each comment.
Instead, it is just showing the user's random id number ``` Updated by #<User:0x007fe8246d3c88> ```
My repo link is https://github.com/nfiona/photo-share/blob/devise/app/views/photos/show.html.erb and my question is about line 28.

(I tried this code: ``` <%= comment.user.email %> ```, this error popped up: _"undefined method `email' for nil:NilClass"_

**Comment by amaseda** [comment]
How are you connecting a user with a comment? I don't see any mention of the current user when you create a comment...

```rb
    def create
      @album = Album.find(params[:album_id])
      @photo = Photo.find(params[:photo_id])
      @comment = @photo.comments.create!(comment_params)
      redirect_to album_photo_path(@album,@photo)
    end
```

Somewhere in the above code you need to indicate that `@comment` belongs to `current_user`. Otherwise, you won't be able to say `@comment.user`

**Comment by amaseda** [comment]
I'm pretty sure the issue might be that you have seeds for albums and comments that are not associated with a user. So when it tries to run, for example, `@comment.user`, it freaks out because that comment does not have a user.

Try getting rid of the content generated by seeds and see if it works if all the data generated is through the app (i.e., using your forms).

**Comment by amaseda** [comment]
Any luck with this? :point_up:

@nfiona

**Comment by nfiona** [comment]
I tried to indicate that @comment belongs to current_user: 
```
def create
      @album = Album.find(params[:album_id])
      @photo = Photo.find(params[:photo_id])
      @comment = @photo.current_user.comments.create!(comment_params)
      redirect_to album_photo_path(@album,@photo)
    end
```
I removed the seed data and restarted my server. But when I tried to generate data through the app, a different error popped up. Now it is not even letting me add photo to my album, which wasn't an issue before.. :/

![screen shot 2017-03-01 at 12 01 37 pm](https://cloud.githubusercontent.com/assets/24783369/23471328/f7957aea-fe76-11e6-8d5c-fbe4d538b079.png)
 @amaseda

**Comment by amaseda** [comment]
The code in the error (uses `params[:id]`) looks different than your snippet (uses `params[:post_id]` -- this is correct). When you use your snippet code, do you still get the same error?

Also, if you're going to associate the user with the comment, I would use `.merge` (as in the below example). I don't think `@album.current_user` is going to work since `current_user` is not a method called by an instance of an album.

```rb
def create
  @photo = Photo.find(params[:photo_id])
  @comment = @photo.comments.create!(comment_params.merge(user: current_user)
  redirect_to album_photo_path(@album,@photo)
end
```

**Comment by amaseda** [comment]
If you're going to associate the current_user with the comment, I would use `.merge` (as in the below example). I don't think `@photo.current_user` is going to work since `current_user` is not a method called by an instance of a Photo.

```rb
def create
  @album = Album.find(params[:album_id])
  @photo = Photo.find(params[:photo_id])
  @comment = @photo.comments.create!(comment_params.merge(user: current_user))
  redirect_to album_photo_path(@album, @photo)
end
```

@nfiona

**Comment by amaseda** [comment]
As for Photos#create not working, if you're creating a photo it does not yet exist, so you should need to call `.find` on the photo class there.

@nfiona

**Comment by nfiona** [comment]
IT IS WORKING!! :heart_eyes: :heart_eyes: :heart_eyes:
THANK YOU! @amaseda

**Comment by amaseda** [comment]
Nice! :+1:
