### ISSUE TITLE
Getting error on rails db:seed

### ISSUE THREAD

**Issue by kwonih1020** [ga-wdi-exercises/project2#867]
https://github.com/kwonih1020/Project2_Travel_Diary/tree/master/app

getting errors on command line when i tried to rails db:seed:
"ActiveRecord::RecordInvalid: Validation failed: User must exist"

**Comment by juancgarcia** [comment]
I think this has to do with the order in your `seeds.rb` file.

Since `Visit` belongs to a `User` you need to supply a user object to `Visit.create(...)`

Make the line `kwon = User.create!(...)` come before `seoul = Visit.create!(...)` and inside `Visit.create!(...)` include the key:value pair `user: kwon` so that `seoul` gets a user assigned.

**Comment by juancgarcia** [comment]
If this problem is solved, please close the issue.

**Comment by kwonih1020** [comment]
Oh ok thank you!
