### ISSUE TITLE
edit option for comments

### ISSUE THREAD

**Issue by StormyRamsey** [ga-wdi-exercises/project2#868]
Hello, 

I am trying to associate the comment edit option with the correct comment id. I can click on the option to update the comment and make the changes, but the changes don't show up. When I add more than one comment and I try to make edits it brings me to the very first comment to make changes. 

This is the code I had in when I received this error: NoMethodError in CommentsController#update
undefined method `update' for nil:NilClass

def update
     @article = Article.find(params[:id])
     @comment.update(params[:id])
       redirect_to @article
   end

I tried making changes to this line:  @comment.update(params[:id])
 I haven't been able to figure how to correct it.  

https://github.com/StormyRamsey/project_2_mommy_blog/commit/def63c25000a3becb1dde967ff2a461ab719b0a5

**Comment by juancgarcia** [comment]
It looks like there might be a few distinct problems here. Let's first work on the error ``undefined method `update` for nil:NilClass``

You found that this is referring to `@comment.update(params[:id])`.
In this line, you're providing a variable named `@comment` and trying to call `.update` with some data.

In the error, ruby is telling us "there is no method named `update` available for instances of `nil`"
This means that the variable `@comment` doesn't actually hold an instance of the `Comment` model as you might otherwise have expected. If we look at the whole `update` method you provided, it should become rapidly apparent that we haven't assigned anything to the variable `@comment` before that line.

In order to call methods on this variable we first need to either assign it an empty instance:
```ruby
@comment = Comment.new
```
or retrieve a record from the database
```ruby
@comment = Comment.find(params[:id])
```
The class method `.find` takes an integer of the database id in order to find and return a unique comment. In the above example we're passing in the `:id` retrieved from the `params` hash which comes from the url (presumably something like this: 'http://localhost:3000/comments/4')

So get a `Comment` instance assigned to `@comment` before the `update` line. Once you resolve the `undefined method` error, we can look further at some of the other issues.

**Comment by StormyRamsey** [comment]
Thanks Juan, my edit option for comments is now updating correctly. Now I am trying to target the edit option to a specific comment, if a user enters more than one comment then they can edit a specific one. I'm going to try and figure it out. 

https://github.com/StormyRamsey/project_2_mommy_blog/commit/0c842d3445725a20e02301addf2dafdee5fc2941

**Comment by AndyWhitley** [comment]
Hi Stormy, are you still having problems with this issue or have you solved it?

**Comment by StormyRamsey** [comment]
Haven't solved it yet. Still working on targeting the edit option to a specific comment. Still researching haven't found anything specific to my problem. I would like for the commenters to be able to edit multiply comments that they have posted if they are having a conversation with other commenters.

**Comment by AndyWhitley** [comment]
In `app/views/articles/show.html.erb`, you would want to add a link to each comment that would direct to `comments#edit`:
```erb
        <% @article.comments.each do |comment| %>
          <p><%= comment.commenter %></p>
          <p><%= comment.body %></p>
        <% end %>
```
should be:
```erb
        <% @article.comments.each do |comment| %>
          <p><%= comment.commenter %></p>
          <p><%= comment.body %></p>
          <p><%= link_to "Edit Comment", edit_article_comment_path(@article, comment) %></p>
        <% end %>
```


Also, why do you have comment resources nested within itself in `routes.rb`:
```rb
  resources :comments do
    resources :comments
  end
```

**Comment by StormyRamsey** [comment]
Everything is working. Just deleted: 
resources :comments do
    resources :comments
  end 
Try to troubleshoot my problem and just created unnecessary routes.

Thanks again.
