### ISSUE TITLE
Issue with adding membership

### ISSUE THREAD

**Issue by cconnerj** [ga-wdi-exercises/project2#874]
def add_membership
    @player = Player.find(params[:id])
    @team = Team.find(params[:team_id])
    @player.memberships.create!
    redirect_to :back
  end
----line in my players controller

error: Validation failed, team must exist

my membership model carries the team_id and player_id and i'm trying to add the team id to the player with the add_membership action, not sure if that can work or not.

**Comment by cconnerj** [comment]
https://github.com/cconnerj/Project2-NHL

if you need it

**Comment by AndyWhitley** [comment]
```rb
@player.memberships.create!(team: @team)
```

**Comment by AndyWhitley** [comment]
@cconnerj Let me know if that fixes it.

**Comment by cconnerj** [comment]
I switched up the code a little bit more, and adding that line did not return any errors, but it the players arent being assigned a team_id when i click add to team, ill ask you guys tomorrow in person so you can see the code.  

Im thinking that the  "adding a membership" action cant put a team_id on a player.... all players start with a nil team_id

**Comment by juancgarcia** [comment]
I think the issue here is with your model relationships. Look back to the [Many-To-Many lesson](https://github.com/ga-wdi-lessons/rails-many-to-many#adding-the-activerecord-relationships-10-minutes--050). You're missing some `has_many` relations and the `through` option.

Your `Membership` model is good with `belongs_to` for both player and team
[app/models/membership.rb](https://github.com/cconnerj/Project2-NHL/blob/master/app/models/membership.rb)

In `Player` you have a `belongs_to` which needs to be `has_many` with a `through`
[app/models/player.rb](https://github.com/cconnerj/Project2-NHL/blob/master/app/models/player.rb)
```ruby
class Player < ActiveRecord::Base
  has_many :memberships
  # The belongs_to line needs to change
  # belongs_to :team, optional: true
  has_many :teams, through: :memberships
end
```

And `Team` is missing `through` and a `has_many`
[app/models/team.rb](https://github.com/cconnerj/Project2-NHL/blob/master/app/models/team.rb)
```ruby
class Team < ActiveRecord::Base
  has_many :memberships
  # has_many :players
  has_many :players, through: :memberships
end
```

Try correcting these model relations, and also I think you should remove the `team_id` from your `players` table if you are sticking with memberships to link players with teams.

**Comment by cconnerj** [comment]
Okay! thanks for the help guys!
