### ISSUE TITLE
Added a key to the devise user table but it doesn't show up on browser 

### ISSUE THREAD

**Issue by tarkzc** [ga-wdi-exercises/project2#891]
<img width="1680" alt="screen shot 2017-06-14 at 11 18 55 am" src="https://user-images.githubusercontent.com/27385620/27140475-a0ed55da-50f3-11e7-8448-84fce4312454.png">

I added :firstname key to the devise user table. 

<img width="744" alt="screen shot 2017-06-14 at 11 19 11 am" src="https://user-images.githubusercontent.com/27385620/27140500-b03f4a02-50f3-11e7-807c-96713ed7dcfa.png">

I want username's :firstname to be shown every page. User's email is showing up but firstname doesn't show up. 

<img width="1680" alt="screen shot 2017-06-14 at 11 19 35 am" src="https://user-images.githubusercontent.com/27385620/27140553-cf719f6a-50f3-11e7-8931-0863bf850786.png">

**Comment by amaseda** [comment]
Did you re-run your migrations after updating the migration? What happens if you run `rails db:migrate:reset`? Youl'll probably need to turn off/on your Rails server.

**Comment by tarkzc** [comment]
Yes I did, it doesn't work

**Comment by amaseda** [comment]
Ah, I think it's because you're not actually using that `configure_permitted_parameters` method you defined. You need to actually call it before the relevant controller actions. Take a look at this example in the Devise documentation, paying particular attention to what is included at the top of the `ApplicationController`.

https://github.com/plataformatec/devise#configuring-models

**Comment by tarkzc** [comment]
Got it. Thanks Adrian.

**Comment by amaseda** [comment]
Nice. Close this one when you've solved the issue / if you run into any other problems relating to this issue post them here!
