### ISSUE TITLE
Prepopulate a f-select form with data

### ISSUE THREAD

**Issue by perryf** [ga-wdi-exercises/project2#906]
Hey, I'm trying to figure out how to have a page auto-select on an f-select form.  I have a many to many relationship between characters and vehicles and I want to be able to to edit my character and have a list of all the vehicles that characters owns that can be added to or removed from.  I have a list working but I can't seem to figure out how to have certain options automatically selected when the user enters the page

**Comment by perryf** [comment]
```  <div class="edit-form">
    <%= f.label :vehicles %>
    <%= f.select :vehicles, Vehicle.all.collect{|vehicle|
      [vehicle.name, vehicle.id]},
      {},
    {:multiple => true, :selected => params[:vehicles_ids]}%>
  </div>```
Trying some stuff among the lines of this

**Comment by jsm13** [comment]
First thing I came across was:

If you are using select (or similar helpers such as collection_select, select_tag) to set a belongs_to association you must pass the name of the foreign key (in the example above city_id), not the name of association itself. If you specify city instead of city_id Active Record will raise an error along the lines of ActiveRecord::AssociationTypeMismatch: City(#17815740) expected, got String(#1138750) when you pass the params hash to Person.new or update. Another way of looking at this is that form helpers only edit attributes. You should also be aware of the potential security ramifications of allowing users to edit foreign keys directly.

from [Rails Guide: Form Helpers 3.2 Select Boxes for Dealing with Models](http://guides.rubyonrails.org/form_helpers.html#select-boxes-for-dealing-with-models)

but that is all assuming a belongs to relationship.

[This SO question](https://stackoverflow.com/a/28128392) seems relevant but still looking.

I'll update when I have more
